name: Deploy app to Azure App Service
on:
  push:
    branches:
      - deploy-to-azure-app-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '27'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2



